#! /bin/bash
#This is a script for rm unneed module and modprobe pcan_usb module.
date
who
sudo modprobe  pcan
sudo rmmod vcan
sudo modprobe -r peak_usb
sudo ip link set can0 up type can bitrate 500000
date
who
